# Pull Request Labeling Rules based on changed files

# Add 'ci' label to any change within the '.github' dir
ci:
- any: ['.github/*', '.github/**/*']


# Add 'business_logic' label to any change within the 'src/artificial_artwork' dir
business_logic:
- any: ['src/artificial_artwork/*', 'src/artificial_artwork/**/*']


# Add 'docs' label to any change within the 'docs' dir
docs:
- any: ['docs/*', 'docs/**/*']


# Add 'test' label to any change within the 'tests' dir
test:
- any: ['tests/*', 'tests/**/*']
