# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  
  # ALL JOBS implied: https://docs.readthedocs.io/en/stable/builds.html
  jobs:
    # post_system_dependencies:
    #   - python3 -m pip install --user poetry
    pre_install:
      - python --version
      # generate compatible and pinned dependencies in pip format, for python3.8
      - python -m pip install poetry
      - python -m poetry export -o req-docs.txt -E docs
    post_install:
      - python -m pip install -e .
    pre_build:
      - python ./scripts/visualize-ga-workflow.py > ./docs/cicd_mermaid.md
      - python ./scripts/visualize-dockerfile.py > ./docs/dockerfile_mermaid.md


# Build documentation in the "docs/" directory with mkdocs
mkdocs:
  configuration: mkdocs.yml

# Extra format only support by Shpinx
# formats:
#   - epub
#   - pdf


# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: req-docs.txt