site_name: Artificial Artwork
repo_name: neural-style-transfer
plugins:
  - search
  - mermaid2
  - mkdocstrings
  - gen-files:
      scripts:
        - scripts/gen_api_refs_pages.py 
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - mkdocs-click
  - pymdownx.highlight
  
nav:
  - Home:
    - "Quick Start": index.md  
    - "CLI": cli.md
  - Developer:
    - "Docker": build-process_DAG.md
  - Code Reference: reference/
